# Site settings
title: Marcio Lourenço
email: marcio.xdev@gmail.com
description:
  en: 'My personal blog, with opinions and comments on technology, development, culture and everything else.'
  pt: 'Meu blog pessoal com opiniões e comentários em tecnologia, desenvolvimento, cultura e tudo mais.'
baseurl: ""
url: "https://xdevelopers.github.io"
flags:
  en: us
  pt: br

author: Marcio Lourenço
twitter_username: marciolou
github_username: XDevelopers

# GitHub override this
safe: true
lsi: false

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /blog/:title/
paginate: 5

defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/pt
    values:
      layout: default
      lang: pt
